apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: M2U5MjE5NDEyYjIxNDgzMjhkYWRjNzg5MGIyYzRiMTA2NWQ0NDhkMWMxYzA2NmVhZTEwMWNhMjA0ODUzY2ZkZjkwNGFmYzIzMDgyYjgzNTI3ZWYxNzUwYTlhMTUzMmM3OWVjNDZiNjQ3ZWYxN2NmYjU3OTIzYmVjYTA0Yjg1ZDY=
